name: SQL Database CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build DACPAC
        run: dotnet build ./DatabaseProjectDEV_DB.sqlproj -c Release
      - name: Deploy to UAT
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_UAT_CONNECTION_STRING }}
          path: './bin/Release/DatabaseProjectDEV_DB.dacpac'
          action: 'publish'
      - name: Deploy to PROD
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_PROD_CONNECTION_STRING }}
          path: './bin/Release/DatabaseProjectDEV_DB.dacpac'
          action: 'publish'
